Fluent interface for launcher (#38)
* Update server.rs

Tests "it_makes_a_server" and  "it_relays_commands_to_the_runner" do not run successfully on windows, apparently Windows does not accept 0.0.0.0. Switched to localhost.

---- server::test::it_relays_commands_to_the_runner stdout ----
        thread 'server::test::it_relays_commands_to_the_runner' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 10049, message: "The requested address is not valid in its context." } }', ../src/libcore\result.rs:788

* Update launcher.rs

Default to localhost on windows

* Update launcher.rs

Copy-paste error fixed

* Replaced current launcher interface

Launcher interface overhauled.
Now has a fluent interface similar to Command & Process.
Added option to add cucumber command line parameters programmatically.

* republished create_config

Removed start & start_with_addr from public API.
Added create_config.

* Update launcher.rs

Updated example in doc

* Update launcher.rs

Changed default address to localhost for all OS

* Update server.rs

Changed addresses to localhost

* readded create_config

* Added new cucumber call to self-tests

* Changed example cuke.rs files
to use the new fluent API.

* Added start to template

* Added IntelliJ files to gitignore

* requested changes
reverted gitignore
Added comment to new api