Change all 0.0.0.0 to 127.0.0.1 to fix Windows (#36)
* Update server.rs

Tests "it_makes_a_server" and  "it_relays_commands_to_the_runner" do not run successfully on windows, apparently Windows does not accept 0.0.0.0. Switched to localhost.

---- server::test::it_relays_commands_to_the_runner stdout ----
        thread 'server::test::it_relays_commands_to_the_runner' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 10049, message: "The requested address is not valid in its context." } }', ../src/libcore\result.rs:788

* Update launcher.rs

Default to localhost on windows

* Update launcher.rs

Copy-paste error fixed

* Update launcher.rs

Changed port from 7879 back to 7878

* Update launcher.rs

Unified default address on all OS

* Update server.rs

Changed address to localhost